juttbadshah=(
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>
"Jutt Badshah","Jutt Badshah","Jutt Badshah","Jutt Ba>